version: "3"

services:
  database:
    build: ./database
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./database/preprocessing:/database/preprocessing
    ports:
      - "25432:5432"
volumes:
  database-data:
