version: "3"

services:
  database:
    build: ./database
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "25432:5432"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/var/opt/gis

volumes:
  database-data:
